### ISSUE TITLE
Explain the term eID

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1936]
The term eID is not well explained in the TYPO3 world. 

I found whenever it is used it is always done  in such a way that it should be obvious what it is and people have been using it for years. But is not explained what it is or the concept behind it etc. This is the case within the docs on docs.typo3.org and outside of the docs.

Also, it looks like this has been mostly deprecated but then, again, not really?

* [Deprecation: #85646 - Deprecate eID implemented as script](Deprecation: #85646 - Deprecate eID implemented as script)

Also, what about middlewares, e.g. typo3/sysext/frontend/Classes/Middleware/EidHandler.php

Here is a question I asked a while ago on Stack Overflow:

https://stackoverflow.com/questions/60282682/what-is-an-eid-in-the-context-of-typo3

## Examples:

_in docs.typo3.org_

1.

> TYPO3 registers an eID script that allows dumping / downloading / referencing files via their FAL ids. Non-public storages use this script to make their files available to view or download.

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Fal/UsingFal/ExamplesFileFolder.html#dumping-a-file-via-eid-script

2.

> Each application class registers request handlers to run a certain request type (e.g. eID or TSFE-logic, or AJAX requests in the Backend).

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Bootstrapping/Index.html#bootstrapping

3.

> When this box is unchecked, the “publicUrl” property of files is replaced by an eID call pointing to a file dumping script

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Fal/Administration/Storages.html

----

_in the source_

```
/**
 * Lightweight alternative to regular frontend requests; used when $_GET[eID] is set.
 * In the future, logic from the EidUtility will be moved to this class, however in most cases
 * a custom PSR-15 middleware will be better suited for whatever job the eID functionality does currently.
 *
 * @internal
 */
class EidHandler implements MiddlewareInterface

```

typo3/sysext/frontend/Classes/Middleware/EidHandler.php

----

`outside of docs.typo3.org`

* https://www.in2code.de/aktuelles/eid-scripte-in-typo3-10/

**Comment by mbrodala** [comment]
Just a clarification: the eID feature itself is not deprecated and there are no plans for this yet AFAIK. What was deprecated back then was registering eID handlers as PHP script files instead of classes with methods.

Instead of eID one can add custom middlewares. And in fact eID is implemented using a middleware in TYPO3. But with a disadvantage: you cannot move execution in the middleware stack. All eID handlers are executed by said middleware at a specific point in the stack. If your handler has dependencies, you cannot continue. While you can move the eID middleware around, you risk breaking other eID handlers this way.

So at least from my POV there is no value in eID anymore nowadays and middlewares should be used.

**Comment by brotkrueml** [comment]
I agree with Mathias. eID is an outdated concept, the Core uses it in some places, some older extensions may use it. But today one should use PSR-15 middlewares. So in my opinion there is no need to explain what is eID and that it should not be used in an extension.
What do you think, @sypets, can this issue be closed?

**Comment by sypets** [comment]
Thank, closing.
