### ISSUE TITLE
Add more diagrams

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#221]
I would like to see more diagrams (or one really good one) which give a general overview of the components, e.g. as in a layer / component diagram or something similar. 

I know, more diagrams exist but somehow they haven't found their way into the documentation, e.g.

- Video 2017 from TYPO3 camp "Mitteldeutschland", Oliver Hader, 17:09: https://www.youtube.com/watch?v=Y6wlsAsLc08&feature=youtu.be&t=1028
- There is a diagram in "Inside TYPO3", but the component "CORE" could be broken down further: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/Introduction/Index.html#system-overview

**Comment by lolli42** [comment]
This issue is a bit too generic, imho: the inside typo3 image has meanwhile been merged into the introduction chapter of core api. Some other diagrams (see formEngine for an example https://docs.typo3.org/typo3cms/CoreApiReference/8.7/ApiOverview/FormEngine/Rendering/Index.html ) are created using the simple text based format from plantuml that is highly protable and the graph source can be added along the rendered image to the repository (see Images/ folder *.plantuml).
If anyone wants to create single graphs, feel free to go ahead.

**Comment by DanielSiepmann** [comment]
If you have specific places @sypets I can try to create those diagrams. I've worked with PlantUML in the past and that should be possible, if I know the parts ;)

**Comment by sypets** [comment]
@DanielSiepmann Thanks for the offer. I did do a draft for this. Must search ...
@lolli42 I'm ok with closing this for now. If Daniel and I come up with something useful, we will contact you.

**Comment by sypets** [comment]
I would like to repoen. The topic has come up at the developer days again. Several people wished for more diagrams. Some people were willing to work on this.

**Comment by linawolf** [comment]
Help is under way with plantUML so I am closing this.
