### ISSUE TITLE
Inconsistency of order in ext_localconf.php

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#2782]
### Current behavior

1. Different order for `defined('TYPO3') or die();`, `use` and `declare strict `in ext_localconf.php.
2. in some examples the content is enclosed in anonymous function, in some not.

### Expected behavior/output

Either do it consistently or leave out the general stuff out of the example snippets

Order should be (I think):

1. declare strict
2. use
3. `defined('TYPO3') or die();`

Is this way in core:ext_localconf (main branch).

Does **not** use anonymous function.

### Examples

1. `defined('TYPO3') or die();` is before use 
https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/Extbase/Reference/FrontendPlugins.html#extbase-registration-of-frontend-plugins

### TYPO3 versions

v11, main

### Possible Solution

see above

**Comment by brotkrueml** [comment]
Hmm, I think the anonymous function can be avoided since 11.5 as the content is wrapped into a global namespace before merging with all other ext_localconf/ext_tables.php files. Has to be checked.

But: For TCA overrides you should use the anonymous function as you most likely declare variables in there and therefore should be scoped. So, we have to explain, when and why to use an anonymous function.

With the order I agree. I would add "declare" and "use" always as people tend to just copy snippets without thinking and then complaining that the example does not work.

**Comment by linawolf** [comment]
I agree, I would also use declare and use  always, especially since the use statements give you valuable information on the FQN of the used classes.

Also when we use literalincludes  the PHP files are linted which should also check the order?

**Comment by linawolf** [comment]
So I just tested it and it seems like our automatic tests do not catch the order of use and if defined. I am wondering if we could add such a check, for now we would have to check it manually

**Comment by sypets** [comment]
Looks like this is done
