### ISSUE TITLE
Recover example how to use SignalSlotDispatcher for v11 and below

### ISSUE THREAD

**Issue by DavidBruchmann** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#3728]
An example how to use SignalSlotDispatcher can be found here:

https://docs.typo3.org/m/typo3/reference-coreapi/6.2/en-us/Internationalization/Translation/Index.html?highlight=signalslot#custom-translation-servers

till here:

https://docs.typo3.org/m/typo3/reference-coreapi/8.7/en-us/Internationalization/Translation/Index.html

SignalSlotDispatcher was existing in a stable version since v4.7. Note that the writing was with underscore ...SignalSlot_Dispatcher...

_Originally posted by @DavidBruchmann in https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/3706#issuecomment-1807449286_

**Comment by DavidBruchmann** [comment]
I didn't check if the example would still work in v11, so it's possible that another example had to be created or found.

**Comment by DavidBruchmann** [comment]
@sbusemann I didn't check if the example would still work in v11, so it's possible that another example had to be created or found.

**Comment by brotkrueml** [comment]
Signal/slots were deprecated with v10, events are in place since that version. If you like you can provide a pull request for v11 - personally, I won't add outdated stuff.

Additionally, the mentioned section with the signal/slot is about adding a custom translation server, in v11 there should be there no example with a deprecated signal/slot anymore, instead the event is described which is the way to go in supported LTS versions:
https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/Localization/TranslationServer/Custom.html

**Comment by DavidBruchmann** [comment]
yes, sure.
Stefan mentioned the problem about missing documentation in the PR, so I just added the info.
If he likes to work on it, fine. I won't spend time on it.

**Comment by brotkrueml** [comment]
We won't work on this. I close this issue for now.
