### ISSUE TITLE
These docs are inconsistent.

### ISSUE THREAD

**Issue by ghost** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#430]
(Tested with version 9.5.5)

From [TYPO3 Explained **latest (9-dev)** -> Introduction -> Code Examples](https://docs.typo3.org/typo3cms/CoreApiReference/Introduction/Index.html#code-examples) ([link to the markdown](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blob/latest/Documentation/Introduction/Index.rst#code-examples)):

> Many of the code examples found in this document come from the TYPO3 Core itself. Quite a few others **come from the "examples" and the "styleguide" extension**. You can install them if you want to try out these examples yourself and use them as a basis for your own stuff.

But when i try to install _TYPO3 CMS Backend Styleguide_ or the _Core Documentation Code Examples_, i get:

> Your TYPO3 version is higher than this extension requires. It requires TYPO3 versions 7.6.0 - 7.99.99

But [Download TYPO3](https://get.typo3.org/) says:

> 7.6 LTS, 6.2 LTS and everything below is no longer supported by the TYPO3 Core Team, consider upgrading or extending support by TYPO3 GmbH.

I found tons of other incosistencies in these docs. Images showing things which are not there in the latest version, Step-by-Step tutorials which result in broken setups (Eg. [Developing TYPO3 Extensions with Extbase and Fluid](https://docs.typo3.org/typo3cms/ExtbaseFluidBook/Index.html)), and so on and so on.

It is true that i can not expect anything from those docs who dont label themself as 'latest (9-dev)'.

However the above [link](https://docs.typo3.org/typo3cms/CoreApiReference/Introduction/Index.html#code-examples) _does_.

The first thing all these docs need is the information, on every page: _TESTED AGAINST VERSIONS A.B.C TO X.Y.Z_ . Then at least i know what to install.

The consequent way, however, is [this](https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/issues/64).

**Comment by sypets** [comment]
Generally, I agree: If the docs are not updated or consistent for one version it can be very confusing.

For the specific example of the styleguide: I will have to check that. The styleguide is actually available for newer TYPO3 version, it is [even available for TYPO3 10](https://github.com/TYPO3/styleguide/blob/master/ext_emconf.php). Can be installed via composer (see [packagist](https://packagist.org/packages/typo3/cms-styleguide)) However, the version in the extension repository is only available for version 7. That is indeed unfortunate and confusing. I assume you did not install via composer?

**Comment by Registrierungsgenervter** [comment]
@sypets Thanks for these links.

Yes, you are right, i did not use composer. Tried with it and was able to install Typo3 9.5.5.

I created the Database manually from within the MySQL Interface, with _utf8_bin_ encoding, and then selected it during installation, as Typo3 itself does not create the database with utf-8 encoding, but reports this as an error under _Environment_ - _Environment Status_.

There is no option to install the example site when using the composer install. It just has two instead of three options (_create empty start page_ and _just go to backend_).

Then i successfully installed the _cms-styleguide_ extension from the[ packagist site you gave](https://packagist.org/packages/typo3/cms-styleguide). I had to run _Maintenance_ -> _Analyze Database Structure_ before i could create the _styleguide page tree_ (from the styleguide, under _TCA/Records_).

---

May i ask how to install packages using composer from extensions.typo3.org? Like the [Official Introduction Package](https://extensions.typo3.org/extension/introduction/) and the [Core Documentation Code Examples](https://extensions.typo3.org/extension/examples/)? Under _Extensions_ it tells me that extensions can only be added using composer. So i can not install from the zips provided there.

May i further ask, where i can have a look at the GLOBALS variable? [Installing extensions](https://docs.typo3.org/typo3cms/CoreApiReference/ExtensionArchitecture/ExtensionManagement/Index.html#installing-extensions) says that this is _available in both frontend and backend_ but i can not find it.

**Comment by sypets** [comment]
I will try to answer your questions, but if you need further assistance I would like to recommend you use one of these methods for support. You will most likely get better support and more people will see your questions:

1) Ask question on [StackOverflow](https://stackoverflow.com). Use tag "typo3". Please beware that StackOverflow may not be the friendliest place for newcomers. If you are already familiar with it, no problem. But if you are just getting started, Slack may actually be the better place to start. 
2) Get yourself a [Slack](https://my.typo3.org/about-mytypo3org/slack/) account and ask TYPO3 question on #typo3-cms channel. If you have general questions, you can ask in #random. 

You will find out more about these 2 methods on https://typo3.org/help

About your questions:

* You can still use TYPO3 without composer. 
* If you use composer, you install extensions (or rather use appropriate composer commands) from the command line, not the backend extension manager. You can however use https://extensions.typo3.org/ to browse through extensions. If you want to do this, you should start from scratch and install TYPO3 via composer as well (or [migrate your project to compser](https://docs.typo3.org/typo3cms/InstallationGuide/MigrateToComposer/Index.html))


I must admit, some things have changed, and I am a little puzzled myself. If you look at the [bootstrap_package](https://extensions.typo3.org/extension/bootstrap_package/), you can see the composer command:

`composer req bk2k/bootstrap-package`

This is missing for introduction extension. I will try to research some more, but for now, please use support methods mentioned above because other people may be more fit to help you with this!

Installation & Upgrade Guide is probably best place for you to start for this:

1) You can also follow the installation & Upgrade guide and install TYPO3 with the base distribution: https://docs.typo3.org/typo3cms/InstallationGuide/QuickInstall/Composer/Index.html
2) ([Installing Distributions with Composer](https://docs.typo3.org/typo3cms/InstallationGuide/In-depth/Distributions/Index.html#installing-distributions-with-composer)) : Introduction package

```
composer require typo3/cms-introduction
composer install
./vendor/bin/typo3 extension:activate bootstrap_package
./vendor/bin/typo3 extension:activate introduction
```

---

If you are not yet familiar with composer. It is always these steps for installing extension:

1. some composer require command (which adds things to composer.json)
2. composer install which does the installing
3. Now the extension is installed, but not yet active (as you can see in extension manager). Thus, the activate (or do this in extension manager). 

---

To look at global variables: In backend for TYPO3 9:  SYSTEM > Configuration > choose drop down at top. But it depends on what you want to do specifically ...

**Comment by Registrierungsgenervter** [comment]
Thank you so much for your time. You rock! Will nag the people on Slack when i have more questions.

**Comment by linawolf** [comment]
Both the extensions and the Manual have been updated in the meantime. Please open a new issue if you find inconsitencies again
