### ISSUE TITLE
Add missing information about the cHash

### ISSUE THREAD

**Issue by schams-net** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#611]
The TYPO3 documentation lacks technical information about the `cHash`.

In particular the content of the article [The Mysteries of cHash](https://typo3.org/article/the-mysteries-of-chash/) could be useful if reviewed, updated, revised, etc. (it's years old and possibly not up-to-date anymore).

Reference: see conversation on [Slack](https://typo3.slack.com/archives/C028JEPJL/p1569917334110400).

**Comment by susannemoog** [comment]
Basic information about the cHash (and caching in general) has been added, see https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/CachingFramework/Index.html?highlight=chash#caching-variants-or-what-is-a-cache-hash - going to close this issue here. If there is still content missing, feel free to improve the chapter :)
