### ISSUE TITLE
ApiOverview/ErrorAndExceptionHandling/Extending Description does not work

### ISSUE THREAD

**Issue by PatricB** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#648]
I tried to extend a ExceptionHandler as descriped in this documentation. But in the end I had to realize that it is not possible on the indicated way. 
The ExceptionHandlers are initialized in the bootstrap process and not again later. At this point, however, no changes to "TYPO3_CONF_VARS" are taken into account. Thus the handlers can only be overwritten by entries in the file "LocalConfiguration.php" or "AddtionalConfiguration.php".
If I miss something, please let me know.

**Comment by sypets** [comment]
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/ErrorAndExceptionHandling/Extending/Index.html

So, you mean, if you put this in AdditionalConfiguration.php for example, it has no effect, because that is evaluated after the excption handling initialization has already taken place?

Thanks for pointing this out. I will try to find someone to have a look at it.

**Comment by sypets** [comment]
I just tested, and it does work for me (in latest master TYPO3 10), meaning if an exception occurs, my handler gets called.

AdditionalConfiguration.php:

`$GLOBALS['TYPO3_CONF_VARS']['SYS']['debugExceptionHandler'] = \Sypets\Exampleerrorhandler\ErrorHandler\ExampleDebugExceptionHandler::class;
`

**Just to test if my exception handler gets called (this code otherwise makes no sense at all):**

```
use TYPO3\CMS\Core\Error\DebugExceptionHandler;


class ExampleDebugExceptionHandler extends DebugExceptionHandler
{
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Formats and echoes the exception as XHTML.
     *
     * @param \Throwable $exception The throwable object.
     */
    public function echoExceptionWeb(\Throwable $exception)
    {
        $exception = new \Exception('Example debug exception');

        parent::echoExceptionWeb($exception);
    }


}
```



Can you check again what exactly does not work?

**Comment by sypets** [comment]
I do think we should update the [docs page](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/ErrorAndExceptionHandling/Extending/Index.html) though and at least write where the code snippets at the top should be put.

**Comment by PatricB** [comment]
> https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/ErrorAndExceptionHandling/Extending/Index.html
> 
> So, you mean, if you put this in AdditionalConfiguration.php for example, it has no effect, because that is evaluated after the excption handling initialization has already taken place?
> 
> Thanks for pointing this out. I will try to find someone to have a look at it.

No, I mean, if I put this into ext_localconf.php it has no effect.

**Comment by sypets** [comment]
See [Slack](https://typo3.slack.com/archives/C03AM9R17/p1573205435381700) for discussion.

See PR: #649
