### ISSUE TITLE
alt_doc.php still referenced for building new record links and edit record links in backend

### ISSUE THREAD

**Issue by luberti** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#73]
As stated in the subject, this doc 

https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Examples/EditLinks/Index.html?highlight=alt_doc

page still references alt_doc.php as the file to use for generating links in the backend for editing and creating new records, even though editOnClick() correctly creates an url with index.php and route param

**Comment by j6s** [comment]
The page should also mention, that correct URLs for edit views can be built using `BackendUtility::getModuleUrl()`. See also: https://github.com/cedricziel/snippets/blob/master/typo3-backend-routing.md

**Comment by sypets** [comment]
I think the entire page could use some proofreading for clarity. I find it very confusing, am not sure if it's up-to-date and the suggested solutions seem overly complicated.

[git blame](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blame/latest/Documentation/ApiOverview/Examples/EditLinks/Index.rst) shows that most of it hasn't been updated for 5 years. 

* "This is not always needed, especially in backend modules using the dispatcher method (which should be all backend modules, since the dispatched was introduced in TYPO3 4.1). " If all backend methods use the dipatcher method since 4.1, then why must this even be mentioned here? Also, this could at least link to an explanation of the dispatcher method (e.g. [feature 69918](https://docs.typo3.org/typo3cms/extensions/core/7.6/Changelog/7.5/Feature-69918-AddPSR-7-basedDispatchingForBackendModules.html))
*

**Comment by sypets** [comment]
For a ViewHelper solution a patch has been generated: https://review.typo3.org/c/56934/

When this is merged, the docs could be updated. See corresponding Changelog: https://review.typo3.org/c/56934/22/typo3/sysext/core/Documentation/Changelog/master/Feature-84983-BEViewHelperForEditDocumentController.rst

**Comment by sypets** [comment]
ViewHelper for edit Record: uri.[editRecord](https://docs.typo3.org/typo3cms/ViewHelperReference/typo3/backend/latest/Uri/EditRecord.html)

and new record: [uri.newRecord](https://docs.typo3.org/typo3cms/ViewHelperReference/typo3/backend/latest/Uri/NewRecord.html)

**Comment by linawolf** [comment]
Got resolved by #1133
