### ISSUE TITLE
Misleading documentation: Using env vars within conditions in site configuration

### ISSUE THREAD

**Issue by tastendruecker** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#997]
The way to refer to environment variables in site configurations as stated in https://docs.typo3.org/m/typo3/reference-coreapi/9.5/en-us/ApiOverview/SiteHandling/UsingEnvVars.html does not work in conditions when e.g. defining base variants, at least with TYPO3 9.5.21:

**Not working** though compliant with the documentation
```
  -
    base: 'https://www.domain.tld'
    condition: '%env(HTTP_HOST)% == "www.domain.tld"'
```

**Working**

```
  -
    base: 'https://www.domain.tld'
    condition: 'getenv("HTTP_HOST") == "www.domain.tld"'
```

Please update the documentation accordingly! Thank you :-)

**Comment by dogawaf** [comment]
The example in the documentation is good: the env var is directly used in `base`, not using `baseVariants` (and its `condition`) at all.
In your case I would not use `baseVariants` at all because the hostname is already in an env var, and it is useless to make a variant on it.

Also, the reason why `condition: 'getenv("HTTP_HOST") == "www.domain.tld"'` is working is because the condition is evaluated by symfony expression language, which gets the value of HTTP_HOST in environment.
I think  `condition: '"%env(HTTP_HOST)%" == "www.domain.tld"'` should work (see the extra quotes around `%env(HTTP_HOST)%`, but I've not tested.

**Comment by sypets** [comment]
@dogawaf Thanks for your feedback!

So, if I understand you correctly, the documentation is correct.

It still might benefit from clarification. But I don't think that is the best place there, I think there is another section about how to deal with environment variables. 

---

@tastendruecker If there is still need to clarify, please raise issue in #typo3-cms channel or on Stack Overflow using "typo3" tag. Thanks. 

---

In any case, pull requests are also welcome, if you have ideas to improve explanations or examples, see also https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocsOfficial/Index.html

**Comment by tastendruecker** [comment]
Thanks dogawaf,

In fact, `condition: '"%env(HTTP_HOST)%" == "www.domain.tld"'`works! It would be nice, if that could be documented somewhere. I couldn't find a single doc where the usage of env vars within conditions was explained. Lots of `applicationContext`  but no env vars. Perhaps you could add an example...

BTW: The usage of `baseVariants` with specific conditions makes sense in our setup/environment ;-)

**Comment by tastendruecker** [comment]
@sypets : I didn't say the documentation war incorrect, just misleading ;-) And i still think the document in question should be updated since it's handling the usage of env vars in site configurations. Perhaps you could just add a line that env vars must be quoted in conditions...

Thanks!
